name: "Build and publish to Docker - CI "
description: "Pushes built artifacts to Docker"
runs:
  using: "composite"
  steps:
  - name: New snapshot
    shell: bash
    run: |
      mvn -B versions:set -DnextSnapshot -DgenerateBackupPoms=false
  - name: Next snapshot
    uses: EndBug/add-and-commit@v7
    with:
      message: next-snapshot  
      branch: develop 
