name: "Build and publish to DockerHub "
description: "Pushes built artifacts to Docker"
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  directory:
    description: "Directory"
    required: true
  github_workspace:
    description: "Github workspace"
    required: true  
  github_token:
    description: "Github Token"
    required: true  
runs:
  using: "composite"
  steps:
    - name: Trimm SHA
      uses: drdeath2609/sha-trim-action@v1.1.1
      with:
        sha-length: 7
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}
    - name: Release
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: mvn compile jib:build -s ${{ inputs.github_workspace }}/.mvn/settings.xml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} 
