name: "Build and publish to Docker - CI "
description: "Pushes built artifacts to Docker"
inputs:
  github_token:
    description: "Github token" 
    required: true
  directory:
    description: "Directory"
    required: true  
runs:
  using: "composite"
  steps:
  - name: Remove snapshot
    working-directory: ${{ inputs.directory }} 
    shell: bash
    run: |
      mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false
  - name: Release version
    uses: EndBug/add-and-commit@v7
    with:
      message: Release version   
  - name: Merge main -> develop
    uses: devmasx/merge-branch@1.4.0
    with:
      type: now
      from_branch: main
      target_branch: develop
      github_token: ${{ inputs.github_token }}         
  
