name: "Build and publish to DockerHub "
description: "Pushes built artifacts to Docker"
inputs:
  directory:
    description: "Directory"
    required: true
  github_workspace:
    description: "Github workspace"
    required: true  
  github_token:
    description: "Github Token"
    required: true  
runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: "11"
        distribution: "adopt"
    - name: Release
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: mvn deploy -s ${{ inputs.github_workspace }}/.mvn/settings.xml
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} 
