name: Automated Download Films - CI
on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - lavanda-automated-download-films/**
      - .github/workflows/automated-download-films-ci.yaml
  workflow_dispatch:    
env:
  DIRECTORY: lavanda-automated-download-films
jobs:
  test-nightly:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Maven
        run: mvn test -s $GITHUB_WORKSPACE/.mvn/settings.xml --file ${{ env.DIRECTORY }}/pom.xml --file ${{ env.DIRECTORY }}/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Send telegram message
        if: always()
        uses: xinthink/action-telegram@v1
        with:
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_TO }}
          jobStatus: ${{ job.status }}
          skipSuccess: true  
  release-build-push-docker:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/workflows/composite/mvn-release
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          directory: ${{ env.DIRECTORY }}
      - uses: ./.github/workflows/composite/build-push-docker-java-image
        with:
          registry_username: ${{ secrets.DOCKER_USERNAME}}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
          directory: ${{ env.DIRECTORY }}
          github_workspace: $GITHUB_WORKSPACE
          github_token: ${{ secrets.GITHUB_TOKEN }} 
  next-snapshot:
    needs: release-build-push-docker
    if: (github.ref == 'refs/heads/main')  && (github.event_name == 'push')  
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2   
        with:
          ref: develop   
      - uses: ./.github/workflows/composite/next-maven-snapshot
        with:
          directory: ${{ env.DIRECTORY }}
  notification:
    needs: [release-build-push-docker, next-snapshot, test-nightly]
    runs-on: ubuntu-latest  
    steps:     
    - name: Send telegram message
      if: ${{ failure() }}
      uses: xinthink/action-telegram@v1
      with:
        botToken: ${{ secrets.TELEGRAM_TOKEN }}
        chatId: ${{ secrets.TELEGRAM_TO }}
        jobStatus: ${{ job.status }}         
        